name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build 

      - name: Create deployment directory
        run: mkdir deploy

      - name: Copy build files to deployment directory
        run: cp -r frontend/build/. deploy/
        run: cp -r backend/. deploy/

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: new-build 
          FOLDER: deploy 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          MESSAGE: "Build: ({sha}) {msg}" 